version: "3.9"
services:
  next-mui-archetype-development:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    ports:
      - "3001:3000"
    links:
      - db-engine-development
  db-engine-development:
    image: mariadb
    ports:
      - "3307:3306"
    expose:
      - 3307
    environment:
      - MARIADB_ROOT_PASSWORD=represion
    volumes:
      - mariadb-data-development:/var/lib/mysql

volumes:
  mariadb-data-development: