version: "3.9"
services:
  db-engine-production:
    image: mariadb
    ports:
      - "3308:3306"
    expose:
      - 3308
    environment:
      - MARIADB_ROOT_PASSWORD=represion
    volumes:
      - mariadb-data-production:/var/lib/mysql

volumes:
  mariadb-data-production: