version: "3.9"
services:
  db-engine-production:
    image: mysql
    ports:
      - "${DOCKER_MYSQL_PORT}:3306"
    expose:
      - ${DOCKER_MYSQL_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DOCKER_MYSQL_DATABASE}
    volumes:
      - mysql-data-production:/var/lib/mysql

volumes:
  mysql-data-production: