version: "3.9"
services:
  db-engine-production:
    image: mariadb
    ports:
      - "${DOCKER_MYSQL_PORT}:3306"
    expose:
      - ${DOCKER_MYSQL_PORT}
    environment:
      - MARIADB_ROOT_PASSWORD=${DOCKER_MYSQL_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DOCKER_MYSQL_DATABASE}
    volumes:
      - mariadb-data-production:/var/lib/mysql

volumes:
  mariadb-data-production: